package Groceries;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.DeleteMapping;

@Controller // Means that the class is a controller
@RequestMapping(path="/grocery") // Means URL's start with /grocery (after application path)
public class GroceryController {
    @Autowired // Means to get the bean called groceryRepository, which is auto-generated by Spring
    private GroceryRepository groceryRepository;

    // @ResponseBody means the returned String is the response, not a view name
    // @RequestParam means that it is a parameter from the GET or POST request
    // (queryparam + formdata + multipart all get combined into "parameters")
    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewGrocery (@RequestParam String itemName, @RequestParam Integer amount) {

        Grocery grocery = new Grocery();
        grocery.setItemName(itemName);
        grocery.setAmount(amount);
        groceryRepository.save(grocery);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Grocery> getAllGroceries() {
        // this returns a JSON or XML with all the groceries
        return groceryRepository.findAll();
    }

    @DeleteMapping(path="/{id}")
    void deleteGrocery(@PathVariable Integer id) {
        System.out.println("Deleting: " + id);
        groceryRepository.deleteById(id);
    }
}
